# Configuration file for the IBI application

# Elasticsearch configuration
elasticsearch:
  ip: 'localhost'
  port: '9200'
  reset: true

########################################
#                                      #
#     Test Only (log to STDOUT)        #
#                                      #
########################################
ckb:
  url: ''
iadt:
  url: ''
rtr:
  url: ''
  username: 'horse-6g'
  password: 'horse-6g'
  email: 'user3@horse-6g.eu'
cas:
  url: ''


########################################
#                                      #
#     UCP Testbed configuration        #
#                                      #
########################################
# ckb:
#   url: 'http://10.19.2.18'
# iadt:
#   url: 'http://10.19.2.23:5005'
# rtr:
#   url: 'http://10.19.2.19:8000'
#   username: 'horse-6g'
#   password: 'horse-6g'
#   email: 'user3@horse-6g.eu'
# cas:
#   url: 'http://10.19.2.21:8000'


########################################
#                                      #
#        UMU Testbed configuration     #
#                                      #
########################################
# ckb:
#   url: 'http://10.208.11.73'
# iadt:
#   url: 'http://10.208.11.74:5005'
# rtr:
#   url: 'http://10.208.11.73:8000'
#   username: 'horse-6g'
#   password: 'horse-6g'
#   email: 'user3@horse-6g.eu'
# cas:
#   url: 'http://10.208.11.73:8000'  # Check port

# CNIT Testbed configuration
# ckb:
#   url: 'http://XXX.XXX.XXX.XXX'
# iadt:
#   url: 'http://XXX.XXX.XXX.XXX:5005'
# rtr:
#   url: 'http://XXX.XXX.XXX.XXX:8000'
#   username: 'horse-6g'
#   password: 'horse-6g'
#   email: 'user3@horse-6g.eu'
# cas:
#   url: 'http://XXX.XXX.XXX.XXX:5005'  # Check port