[project]
name = "horse-ibi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.13",
    "pydantic>=2.11.7",
    "pyyaml>=6.0.2",
    "requests==2.31.0",
    "urllib3==2.1.0",
    "uvicorn>=0.34.3",
]
