@host = 10.208.11.73:8002

### Demo 0
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "prevention",
    "threat": "dns_amplification",
    "host": ["dns-c1"],
    "duration": 1200
}

### Demo 0 - Prevention / Prediction (2025-10-29)
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "prevention",
    "threat": "ddos_downlink",
    "host": ["172.22.0.7"],
    "duration": 600
}

#### Demo 1
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "mitigation",
    "threat": "ddos_amplification",
    "host": ["172.22.1.1"],
    "duration": 600
}

### Demo 2
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "prevention",
    "threat": "dns_amplification",
    "host": ["dns-c2", "dns-c3"],
    "duration": 600
}


### Demo 3
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "prevention",
    "threat": "ddos_downlink",
    "host": ["dns-c2", "dns-c3"],
    "duration": 1200
}

### Demo 5
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "mitigation",
    "threat": "multidomain",
    "host": ["dns-cnit", "dns-upc"],
    "duration": 600
}

### Demo 6-1
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "detection",
    "threat": "pfcp_deletion",
    "host": ["192.168.56.5", "192.168.56.3"],
    "duration": 600
}

### Demo 6-2
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "detection",
    "threat": "pfcp_establishment",
    "host": ["192.168.56.5", "192.168.56.3"],
    "duration": 600
}

### Demo 6-3
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "detection",
    "threat": "pfcp_modification",
    "host": ["192.168.56.5", "192.168.56.3"],
    "duration": 600
}


### Demo 7
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "mitigation",
    "threat": "nf_exposure",
    "host": ["192.168.56.5", "192.168.56.3"],
    "duration": 600
}

### Demo 8-1
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "detection",
    "threat": "signaling_pfcp",
    "host": ["192.168.56.5", "192.168.56.3"],
    "duration": 600
}

### Demo 8-2
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "detection",
    "threat": "pfcp_deletion",
    "host": ["192.168.56.5", "192.168.56.3"],
    "duration": 600
}

### Demo 8-3
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "detection",
    "threat": "pfcp_establishment",
    "host": ["192.168.56.5", "192.168.56.3"],
    "duration": 600
}

### Demo 8-4
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "detection",
    "threat": "pfcp_modification",
    "host": ["192.168.56.5", "192.168.56.3"],
    "duration": 600
}

### Demo 9
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "mitigation",
    "threat": "poisoning_and_amplification",
    "host": ["192.168.56.5", "192.168.56.3"],
    "duration": 600
}

### Demo 10 -- HOLO
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "mitigation",
    "threat": "api_exposure",
    "host": ["ue-1", "ue-2", "ue-3", "ue-4", "ue-9"],
    "duration": 1200
}

### Demo 10 -- HOLO
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "mitigation",
    "threat": "ddos_amplification",
    "host": ["ue-1", "ue-2", "ue-3", "ue-4", "ue-9"],
    "duration": 1200
}

### Demo 10 -- HOLO
POST http://{{host}}/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "prevention",
    "threat": "ddos_amplification",
    "host": ["ue-11"],
    "duration": 1200
}