# DTE

###
POST http://127.0.0.1:8000/intents HTTP/1.1
content-type: application/json

{
    "intent_type": "mitigation",
    "threat": "hello_world",
    "host": [""],
    "duration": 600
}



# ElasticSearch REST API calls for testing

###
GET http://127.0.0.1:9200/intents/_search?pretty HTTP/1.1

###
DELETE  http://127.0.0.1:9200/intents HTTP/1.1
