{
  #your IP and port with which to provision your APIs
  'ip': '172.21.0.1',
  'port': '7777',
  
  #ip and port where elasticsearch runs on your system
  'elasticsearch_ip': '127.0.0.1',
  'elasticsearch_port': '9200',
  
  
  #API ENDPOINTS
  
  #PROVISIONED BY THE IBI
  #eg API endpoint for sending intents: "http://172.21.0.1:7777/intents"
  #the API for sending intents is where the DTE sends intents
  'to_enter_intents': '/intents',
  #the receive_whatif API is the API for receiving what-if answers from the SAN
  'to_receive_whatif': '/whatif_receives',
  #the stored_intents API is for viewing and deleting existing intents
  'to_view_or_delete_intents': '/stored_intents',
  
  #PROVISIONED BY OTHER MODULES
  #the API for sending workflow is the API for sending workflows to RTR
  'to_send_workflow': '/workflows',
  'rtr_api_url': 'http://172.21.0.1:7777/workflows',
  #the send_whatif API is the API for sending what-if questions to the SAN
  'to_send_whatif': '/whatif_sends',
  'san_api_url': 'http://172.21.0.1:7777/whatif_sends',
   
  
  #to clear existing intent store if you want, otherwise, set it as 'false'
  'clear_intent_store': 'true'
}
