"""
    Definition of constants
"""

class Const:
    # Application
    APP_NAME = "HORSE-IBI"
    APP_VERSION = "0.0.3a"

    # Server related
    APP_HOST = "0.0.0.0"
    APP_PORT = 8000

    # Intent status
    INTENT_STATUS_NEW = "INTENT_STATUS_NEW"
    INTENT_STATUS_IN_PROGRESS = "INTENT_STATUS_IN_PROGRESS"
    INTENT_STATUS_RENEWED = "INTENT_STATUS_RENEWED"
    INTENT_STATUS_UNDER_MITIGATION = "INTENT_STATUS_UNDER_MITIGATION"
    INTENT_STATUS_NDT_SENT = "INTENT_STATUS_NDT_SENT"
    INTENT_STATUS_NDT_VALIDATED = "INTENT_STATUS_TIMEOUT"
    INTENT_STATUS_MITIGATED = "INTENT_STATUS_MITIGATED"

    # Intent processing loop
    THREAD_INTENT_WAIT = 1.0

    # Elasticsearch indexes
    INTENTS_INDEX = "intents"
    MITIGATION_INDEX = "mitigations"

    IADT_PPS_THRESHOLD = 2.0

